### PR TITLE
(TK-374) Remove obsolete SSL ciphers

### PR DESCRIPTION
**Pull request by adrienthebo**

### CODE REVIEW

**Comment by adrienthebo** [comment]
Done.

I remember telling myself to update the documentation when I opened `jetty_config.clj` and then managed to promptly forget. Oi.

**Comment by jsane** [comment]
My comment may not count but will provide my $0.02 anyway. Looks ok to me as well.

**Comment by camlow325** [comment]
@jsane Your comment definitely counts.  😄  Thanks for weighing in!

**Pull request merged**
